name: Publish to Nexus
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Tag version
        run: git tag ${{ github.event.release.tag_name }} -f &&
             git push --tags origin --force
      - name: Setup Java and Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}
        run: mvn --batch-mode deploy
